// ============================================================
// CampusCode — Comprehensive Database Seed Script
// ============================================================
// Run with: npx prisma db seed
// Populates all real student profiles, client organizations,
// marketplace products, projects, and all 12 solution requests
// directly into Neon PostgreSQL with relational consistency.
// ============================================================

import { PrismaClient, UserRole, StudentLevel, ProjectStatus, TaskStatus, TaskPriority, ProductStatus, SolutionRequestStatus, ProposalStatus, ContractStatus, MilestoneStatus } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting comprehensive database seed to Neon PostgreSQL...");

  // 1. Clear existing sample records cleanly
  await prisma.notification.deleteMany();
  await prisma.message.deleteMany();
  await prisma.conversationParticipant.deleteMany();
  await prisma.conversation.deleteMany();
  await prisma.review.deleteMany();
  await prisma.transaction.deleteMany();
  await prisma.contractMilestone.deleteMany();
  await prisma.contract.deleteMany();
  await prisma.proposalMilestone.deleteMany();
  await prisma.proposal.deleteMany();
  await prisma.solutionRequest.deleteMany();
  await prisma.order.deleteMany();
  await prisma.productReview.deleteMany();
  await prisma.product.deleteMany();
  await prisma.comment.deleteMany();
  await prisma.subTask.deleteMany();
  await prisma.task.deleteMany();
  await prisma.projectMilestone.deleteMany();
  await prisma.projectMember.deleteMany();
  await prisma.project.deleteMany();
  await prisma.badge.deleteMany();
  await prisma.studentProfile.deleteMany();
  await prisma.clientProfile.deleteMany();
  await prisma.tag.deleteMany();
  await prisma.category.deleteMany();
  await prisma.user.deleteMany();

  console.log("🧹 Cleaned database tables.");

  // Common password hash
  const defaultPassword = await bcrypt.hash("password123", 12);

  // 2. Categories
  const categoriesData = [
    { name: "Full-Stack Templates", slug: "templates", icon: "Layout", productCount: 4, requestCount: 8 },
    { name: "Web Applications", slug: "web", icon: "Globe", productCount: 6, requestCount: 12 },
    { name: "AI & Machine Learning", slug: "ai-ml", icon: "Brain", productCount: 4, requestCount: 14 },
    { name: "Mobile Applications", slug: "mobile", icon: "Smartphone", productCount: 3, requestCount: 9 },
    { name: "SaaS Starter Kits", slug: "saas", icon: "Cloud", productCount: 3, requestCount: 7 },
    { name: "UI Kits & Dashboards", slug: "ui-kits", icon: "Palette", productCount: 4, requestCount: 6 },
    { name: "APIs & Developer Tools", slug: "api", icon: "Terminal", productCount: 3, requestCount: 5 },
    { name: "Data Science", slug: "data-science", icon: "BarChart3", productCount: 2, requestCount: 4 },
    { name: "Automation & Scripts", slug: "automation", icon: "Zap", productCount: 2, requestCount: 6 },
  ];

  for (const cat of categoriesData) {
    await prisma.category.create({ data: cat });
  }
  console.log("✅ Seeded categories.");

  // 3. Students
  const studentsData = [
    {
      id: "u1",
      name: "Aarav Sharma",
      email: "aarav@campuscode.dev",
      role: UserRole.STUDENT,
      isVerified: true,
      college: "Delhi Tech University",
      degree: "B.Tech CSE",
      graduationYear: 2026,
      skills: ["React", "Node.js", "Python", "TypeScript", "Next.js", "PostgreSQL", "Machine Learning"],
      github: "aaravsharma",
      linkedin: "aaravsharma",
      bio: "Full-stack developer passionate about building scalable products and open-source tooling.",
      level: StudentLevel.EXPERT,
      rating: 4.9,
      reviewCount: 47,
      totalSales: 87,
      totalEarnings: 124500,
      completedProjects: 12,
      portfolioUrl: "@aarav",
    },
    {
      id: "u2",
      name: "Priya Sharma",
      email: "priya@campuscode.dev",
      role: UserRole.STUDENT,
      isVerified: true,
      college: "IIT Delhi",
      degree: "B.Tech AI & ML",
      graduationYear: 2027,
      skills: ["Python", "TensorFlow", "PyTorch", "React", "FastAPI", "scikit-learn", "OpenCV"],
      github: "priyasharma",
      linkedin: "priyasharma",
      bio: "AI/ML enthusiast building intelligent solutions. Research intern focusing on computer vision.",
      level: StudentLevel.BUILDER,
      rating: 4.8,
      reviewCount: 32,
      totalSales: 54,
      totalEarnings: 89000,
      completedProjects: 8,
      portfolioUrl: "@priya",
    },
    {
      id: "u3",
      name: "Rahul Mehta",
      email: "rahul@campuscode.dev",
      role: UserRole.STUDENT,
      isVerified: true,
      college: "BITS Pilani",
      degree: "M.Tech Software Eng.",
      graduationYear: 2026,
      skills: ["Java", "Spring Boot", "React", "PostgreSQL", "Docker", "Kubernetes", "Redis"],
      github: "rahulmehta",
      linkedin: "rahulmehta",
      bio: "Backend specialist building high-concurrency systems and enterprise ERP architectures.",
      level: StudentLevel.TOP_DEVELOPER,
      rating: 4.7,
      reviewCount: 38,
      totalSales: 45,
      totalEarnings: 156000,
      completedProjects: 15,
      portfolioUrl: "@rahul",
    },
    {
      id: "u4",
      name: "Ananya Gupta",
      email: "ananya@campuscode.dev",
      role: UserRole.STUDENT,
      isVerified: true,
      college: "VIT Vellore",
      degree: "B.Tech CSE",
      graduationYear: 2027,
      skills: ["Flutter", "Dart", "React Native", "Firebase", "Node.js", "MongoDB"],
      github: "ananyagupta",
      linkedin: "ananyagupta",
      bio: "Mobile app developer. Built 10+ production mobile apps with Flutter & modern UI.",
      level: StudentLevel.BUILDER,
      rating: 4.6,
      reviewCount: 21,
      totalSales: 38,
      totalEarnings: 67000,
      completedProjects: 6,
      portfolioUrl: "@ananya",
    },
    {
      id: "u5",
      name: "Arjun Patel",
      email: "arjun@campuscode.dev",
      role: UserRole.STUDENT,
      isVerified: true,
      college: "IIIT Hyderabad",
      degree: "B.Tech IT",
      graduationYear: 2026,
      skills: ["Python", "Django", "React", "PostgreSQL", "Redis", "Docker", "AWS"],
      github: "arjunpatel",
      linkedin: "arjunpatel",
      bio: "Full-stack developer specializing in Python ecosystems, microservices, and DevOps automation.",
      level: StudentLevel.CONTRIBUTOR,
      rating: 4.5,
      reviewCount: 15,
      totalSales: 22,
      totalEarnings: 42000,
      completedProjects: 4,
      portfolioUrl: "@arjun",
    },
    {
      id: "u6",
      name: "Sneha Reddy",
      email: "sneha@campuscode.dev",
      role: UserRole.STUDENT,
      isVerified: true,
      college: "NIT Warangal",
      degree: "B.Tech CSE",
      graduationYear: 2027,
      skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Figma", "Node.js", "Recharts"],
      github: "snehareddy",
      linkedin: "snehareddy",
      bio: "Frontend engineer & UI designer. Creating pixel-perfect interfaces with modern web tech.",
      level: StudentLevel.BUILDER,
      rating: 4.8,
      reviewCount: 28,
      totalSales: 63,
      totalEarnings: 78000,
      completedProjects: 7,
      portfolioUrl: "@sneha",
    },
    {
      id: "u7",
      name: "Vikram Singh",
      email: "vikram@campuscode.dev",
      role: UserRole.STUDENT,
      isVerified: true,
      college: "DTU Delhi",
      degree: "B.Tech ECE",
      graduationYear: 2026,
      skills: ["IoT", "Embedded C", "Python", "MQTT", "Node.js", "React", "Raspberry Pi"],
      github: "vikramsingh",
      linkedin: "vikramsingh",
      bio: "Embedded systems engineer connecting hardware with full-stack IoT cloud dashboards.",
      level: StudentLevel.CONTRIBUTOR,
      rating: 4.6,
      reviewCount: 19,
      totalSales: 29,
      totalEarnings: 53000,
      completedProjects: 5,
      portfolioUrl: "@vikram",
    },
    {
      id: "u8",
      name: "Rohan Joshi",
      email: "rohan@campuscode.dev",
      role: UserRole.STUDENT,
      isVerified: true,
      college: "IIT Bombay",
      degree: "B.Tech Data Science",
      graduationYear: 2026,
      skills: ["Python", "Pandas", "scikit-learn", "FastAPI", "React", "D3.js", "SQL"],
      github: "rohanjoshi",
      linkedin: "rohanjoshi",
      bio: "Data science and visualization specialist. Translating complex analytics into clean interactive dashboards.",
      level: StudentLevel.EXPERT,
      rating: 4.9,
      reviewCount: 41,
      totalSales: 76,
      totalEarnings: 118000,
      completedProjects: 11,
      portfolioUrl: "@rohan",
    },
  ];

  for (const s of studentsData) {
    await prisma.user.create({
      data: {
        id: s.id,
        name: s.name,
        email: s.email,
        password: defaultPassword,
        role: s.role,
        isVerified: s.isVerified,
        studentProfile: {
          create: {
            college: s.college,
            degree: s.degree,
            graduationYear: s.graduationYear,
            skills: s.skills,
            github: s.github,
            linkedin: s.linkedin,
            bio: s.bio,
            level: s.level,
            rating: s.rating,
            reviewCount: s.reviewCount,
            totalSales: s.totalSales,
            totalEarnings: s.totalEarnings,
            completedProjects: s.completedProjects,
            portfolioUrl: s.portfolioUrl,
            badges: {
              create: [
                { name: "Verified Student", icon: "✓", description: "Identity and college enrolled" },
                { name: "Top Rated Builder", icon: "⭐", description: "Maintained 4.5+ star rating" },
              ],
            },
          },
        },
      },
    });
  }
  console.log("✅ Seeded 8 verified student developer accounts.");

  // 4. Clients
  const clientsData = [
    {
      id: "c1",
      name: "Vikram Malhotra",
      email: "client@techstart.io",
      role: UserRole.CLIENT,
      organization: "TechStart Innovations",
      website: "https://techstart.io",
      description: "Fast-growing startup building automated HR and enterprise tooling.",
      rating: 4.9,
      reviewCount: 15,
      totalSpent: 185000,
      projectsPosted: 6,
    },
    {
      id: "c2",
      name: "Pooja Rao",
      email: "contact@edutechglobal.com",
      role: UserRole.CLIENT,
      organization: "EduTech Global",
      website: "https://edutechglobal.com",
      description: "EdTech platform modernizing higher education portals and attendance automation.",
      rating: 4.8,
      reviewCount: 11,
      totalSpent: 120000,
      projectsPosted: 4,
    },
    {
      id: "c3",
      name: "Dr. Amit Verma",
      email: "dr.verma@healthfirst.in",
      role: UserRole.CLIENT,
      organization: "HealthFirst Solutions",
      website: "https://healthfirst.in",
      description: "Healthcare clinic management network providing digital patient portals.",
      rating: 4.9,
      reviewCount: 8,
      totalSpent: 95000,
      projectsPosted: 3,
    },
    {
      id: "c4",
      name: "Sanjay Singhania",
      email: "events@campusevents.co",
      role: UserRole.CLIENT,
      organization: "Campus Events Co.",
      website: "https://campusevents.co",
      description: "Inter-college cultural and technical event coordination syndicate.",
      rating: 4.7,
      reviewCount: 19,
      totalSpent: 145000,
      projectsPosted: 5,
    },
  ];

  for (const c of clientsData) {
    await prisma.user.create({
      data: {
        id: c.id,
        name: c.name,
        email: c.email,
        password: defaultPassword,
        role: c.role,
        isVerified: true,
        clientProfile: {
          create: {
            organization: c.organization,
            website: c.website,
            description: c.description,
            rating: c.rating,
            reviewCount: c.reviewCount,
            totalSpent: c.totalSpent,
            projectsPosted: c.projectsPosted,
          },
        },
      },
    });
  }
  console.log("✅ Seeded 4 client organizations.");

  // 5. Marketplace Products
  const productsData = [
    {
      id: "p1",
      name: "AI Resume Analyzer",
      slug: "ai-resume-analyzer",
      description: "AI-powered resume analysis and scoring system with NLP.",
      shortDescription: "Parse, analyze, and score candidate resumes against job descriptions with NLP.",
      category: "ai-ml",
      price: 499,
      isFree: false,
      status: ProductStatus.PUBLISHED,
      sellerId: "u1",
      technologies: ["React", "Python", "FastAPI", "TensorFlow", "PostgreSQL"],
      tags: ["AI", "NLP", "Resume", "HR Tech"],
      features: ["Resume parsing with NLP", "Job description matching", "ATS score calculation", "Skill gap analysis", "Improvement suggestions", "Batch processing", "Export reports", "REST API"],
      requirements: ["Python 3.9+", "Node.js 18+", "PostgreSQL 14+"],
      installation: "1. Clone repository\n2. pip install -r requirements.txt\n3. npm install\n4. npm run dev",
      documentation: "Full API documentation available at /docs endpoint.",
      version: "2.1.0",
      rating: 4.8,
      reviewCount: 124,
      salesCount: 124,
      license: "Commercial",
    },
    {
      id: "p2",
      name: "College ERP System",
      slug: "college-erp-system",
      description: "Complete college management system with student, faculty, and admin modules.",
      shortDescription: "Full-featured Enterprise Resource Planning system for educational institutions.",
      category: "web",
      price: 1999,
      isFree: false,
      status: ProductStatus.PUBLISHED,
      sellerId: "u3",
      technologies: ["React", "Node.js", "Express", "PostgreSQL", "Redis"],
      tags: ["ERP", "Education", "Management", "Full Stack"],
      features: ["Student management", "Faculty management", "Course scheduling", "Attendance tracking", "Grade management", "Fee management", "Library module", "Report generation"],
      requirements: ["Node.js 18+", "PostgreSQL 14+", "Redis 7+"],
      installation: "1. npm install\n2. Configure .env\n3. Run migrations\n4. npm run dev",
      documentation: "Comprehensive docs included with API reference.",
      version: "3.0.0",
      rating: 4.6,
      reviewCount: 67,
      salesCount: 67,
      license: "Commercial",
    },
    {
      id: "p3",
      name: "E-Commerce Starter Kit",
      slug: "ecommerce-starter-kit",
      description: "Production-ready e-commerce template with payment integration.",
      shortDescription: "Complete e-commerce solution with cart, checkout, payment gateway, and admin panel.",
      category: "templates",
      price: 799,
      isFree: false,
      status: ProductStatus.PUBLISHED,
      sellerId: "u6",
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Prisma", "PostgreSQL", "Razorpay"],
      tags: ["E-Commerce", "Template", "Starter Kit", "Payment"],
      features: ["Product catalog", "Shopping cart", "Secure checkout", "Payment integration", "Order management", "Inventory tracking", "Admin dashboard", "Customer accounts"],
      requirements: ["Node.js 18+", "PostgreSQL 14+"],
      installation: "1. npm install\n2. npx prisma migrate dev\n3. npm run dev",
      documentation: "Detailed setup guide and customization docs included.",
      version: "1.5.0",
      rating: 4.7,
      reviewCount: 89,
      salesCount: 89,
      license: "MIT",
    },
    {
      id: "p4",
      name: "Smart Expense Tracker",
      slug: "smart-expense-tracker",
      description: "AI-powered personal finance tracker with budget insights.",
      shortDescription: "Intelligent expense tracking app with receipt OCR and budget recommendations.",
      category: "mobile",
      price: 599,
      isFree: false,
      status: ProductStatus.PUBLISHED,
      sellerId: "u4",
      technologies: ["Flutter", "Dart", "Firebase", "TensorFlow Lite", "Node.js"],
      tags: ["Finance", "AI", "Mobile", "Analytics"],
      features: ["Receipt scanning (OCR)", "Auto-categorization", "Budget tracking", "Spending analytics", "Multi-currency", "Recurring expenses", "Export reports"],
      requirements: ["Flutter 3.10+", "Firebase project"],
      installation: "1. flutter pub get\n2. Configure Firebase\n3. flutter run",
      documentation: "Architecture guide and Flutter setup included.",
      version: "2.0.0",
      rating: 4.5,
      reviewCount: 42,
      salesCount: 42,
      license: "Commercial",
    },
    {
      id: "p5",
      name: "Face Recognition Attendance",
      slug: "face-recognition-attendance",
      description: "Real-time face recognition based attendance system.",
      shortDescription: "Automated attendance system using deep learning face detection & anti-spoofing.",
      category: "ai-ml",
      price: 699,
      isFree: false,
      status: ProductStatus.PUBLISHED,
      sellerId: "u2",
      technologies: ["Python", "OpenCV", "TensorFlow", "Flask", "React", "PostgreSQL"],
      tags: ["Face Recognition", "Attendance", "Computer Vision", "Deep Learning"],
      features: ["Real-time face detection", "Face recognition", "Anti-spoofing", "Attendance reports", "Student database", "Multi-camera support", "Export to CSV/Excel"],
      requirements: ["Python 3.9+", "Webcam"],
      installation: "1. pip install -r requirements.txt\n2. python app.py",
      documentation: "Includes pre-trained model setup and camera calibration.",
      version: "1.3.0",
      rating: 4.4,
      reviewCount: 56,
      salesCount: 56,
      license: "Commercial",
    },
    {
      id: "p6",
      name: "React Admin Dashboard",
      slug: "react-admin-dashboard",
      description: "Premium admin dashboard template with 50+ components.",
      shortDescription: "Feature-rich admin dashboard built with React, TypeScript, and Tailwind CSS.",
      category: "ui-kits",
      price: 0,
      isFree: true,
      status: ProductStatus.PUBLISHED,
      sellerId: "u6",
      technologies: ["React", "TypeScript", "Tailwind CSS", "Recharts", "React Hook Form"],
      tags: ["Dashboard", "Admin", "Template", "UI Kit"],
      features: ["50+ components", "10+ page templates", "Dark/Light mode", "Responsive design", "Chart integrations", "Form components", "Data tables"],
      requirements: ["Node.js 18+"],
      installation: "1. npm install\n2. npm run dev",
      documentation: "Storybook documentation & Figma components included.",
      version: "4.0.0",
      rating: 4.9,
      reviewCount: 234,
      salesCount: 1247,
      license: "MIT",
    },
    {
      id: "p7",
      name: "Job Portal Platform",
      slug: "job-portal-platform",
      description: "Full-featured job portal with AI matching and analytics.",
      shortDescription: "Job portal platform connecting employers and candidates with AI skill matching.",
      category: "web",
      price: 1499,
      isFree: false,
      status: ProductStatus.PUBLISHED,
      sellerId: "u1",
      technologies: ["Next.js", "Node.js", "PostgreSQL", "Redis"],
      tags: ["Job Portal", "HR", "Full Stack", "AI"],
      features: ["AI job matching", "Advanced search", "Resume builder", "Company profiles", "Application tracking", "Interview scheduling", "Analytics dashboard"],
      requirements: ["Node.js 18+", "PostgreSQL 14+"],
      installation: "1. npm install\n2. npx prisma migrate dev\n3. npm run dev",
      documentation: "Full API docs and developer guides included.",
      version: "2.0.0",
      rating: 4.6,
      reviewCount: 45,
      salesCount: 45,
      license: "Commercial",
    },
    {
      id: "p8",
      name: "Real-time Chat Application",
      slug: "realtime-chat-application",
      description: "Scalable real-time chat with WebSocket, groups, and file sharing.",
      shortDescription: "Modern chat application with rooms, typing indicators, read receipts, and media attachments.",
      category: "web",
      price: 399,
      isFree: false,
      status: ProductStatus.PUBLISHED,
      sellerId: "u5",
      technologies: ["React", "Node.js", "Socket.io", "PostgreSQL", "Redis"],
      tags: ["Chat", "Real-time", "WebSocket", "Messaging"],
      features: ["Real-time messaging", "Group chats", "File sharing", "Typing indicators", "Read receipts", "Message reactions", "Push notifications"],
      requirements: ["Node.js 18+", "PostgreSQL 14+", "Redis 7+"],
      installation: "1. npm install\n2. npm run dev",
      documentation: "WebSocket architecture docs included.",
      version: "1.2.0",
      rating: 4.3,
      reviewCount: 31,
      salesCount: 31,
      license: "MIT",
    },
    {
      id: "p9",
      name: "Inventory Management System",
      slug: "inventory-management-system",
      description: "Complete inventory management with barcode scanning and analytics.",
      shortDescription: "Track stock, purchase orders, supplier management, and low stock notifications.",
      category: "web",
      price: 899,
      isFree: false,
      status: ProductStatus.PUBLISHED,
      sellerId: "u3",
      technologies: ["React", "Node.js", "Express", "PostgreSQL", "Chart.js"],
      tags: ["Inventory", "Business", "Management", "Analytics"],
      features: ["Barcode scanning", "Stock tracking", "Purchase orders", "Supplier management", "Low stock alerts", "Sales tracking", "Analytics dashboard"],
      requirements: ["Node.js 18+", "PostgreSQL 14+"],
      installation: "1. npm install\n2. npm run dev",
      documentation: "User manual and database schema included.",
      version: "1.0.0",
      rating: 4.5,
      reviewCount: 28,
      salesCount: 28,
      license: "Commercial",
    },
    {
      id: "p10",
      name: "Health Analytics Dashboard",
      slug: "health-analytics-dashboard",
      description: "Machine learning dashboard for health analytics and predictive risk modeling.",
      shortDescription: "Predictive health analytics with interactive SHAP visual explanations.",
      category: "ai-ml",
      price: 0,
      isFree: true,
      status: ProductStatus.PUBLISHED,
      sellerId: "u8",
      technologies: ["Python", "scikit-learn", "FastAPI", "React", "Plotly"],
      tags: ["Healthcare", "ML", "Dashboard", "Prediction"],
      features: ["Risk prediction models", "Interactive charts", "SHAP model explanations", "Patient analytics", "Report generation"],
      requirements: ["Python 3.9+", "Node.js 18+"],
      installation: "1. pip install -r requirements.txt\n2. python main.py",
      documentation: "Includes model documentation and research references.",
      version: "1.5.0",
      rating: 4.7,
      reviewCount: 93,
      salesCount: 456,
      license: "MIT",
    },
    {
      id: "p11",
      name: "Next.js SaaS Boilerplate",
      slug: "nextjs-saas-boilerplate",
      description: "Production-ready SaaS starter with auth, billing, and team workspaces.",
      shortDescription: "Complete full-stack starter with multi-tenancy, Stripe subscriptions, and dark mode.",
      category: "saas",
      price: 2499,
      isFree: false,
      status: ProductStatus.PUBLISHED,
      sellerId: "u1",
      technologies: ["Next.js", "TypeScript", "Prisma", "PostgreSQL", "Tailwind CSS", "Stripe"],
      tags: ["SaaS", "Boilerplate", "Starter", "Production"],
      features: ["Authentication (OAuth, email)", "Subscription billing", "Team management", "RBAC", "Admin dashboard", "Email templates", "API rate limiting"],
      requirements: ["Node.js 18+", "PostgreSQL 14+"],
      installation: "1. npm install\n2. npx prisma migrate dev\n3. npm run dev",
      documentation: "Extensive architecture guide and deployment recipes included.",
      version: "2.4.0",
      rating: 4.9,
      reviewCount: 37,
      salesCount: 37,
      license: "Commercial",
    },
    {
      id: "p12",
      name: "REST API Toolkit",
      slug: "rest-api-toolkit",
      description: "Comprehensive REST API toolkit with auth, validation, and Swagger docs.",
      shortDescription: "Fast, robust REST API starter with Zod validation, JWT authentication, and rate limiting.",
      category: "api",
      price: 299,
      isFree: false,
      status: ProductStatus.PUBLISHED,
      sellerId: "u5",
      technologies: ["Node.js", "Express", "TypeScript", "PostgreSQL", "Jest", "Swagger"],
      tags: ["API", "Backend", "Toolkit", "REST"],
      features: ["JWT authentication", "Request validation (Zod)", "Rate limiting", "Structured logging", "Error handling", "Swagger docs", "Testing suite"],
      requirements: ["Node.js 18+", "PostgreSQL 14+"],
      installation: "1. npm install\n2. npm run dev",
      documentation: "Auto-generated Swagger documentation at /api-docs.",
      version: "2.3.0",
      rating: 4.4,
      reviewCount: 52,
      salesCount: 52,
      license: "MIT",
    },
  ];

  for (const prod of productsData) {
    await prisma.product.create({
      data: {
        id: prod.id,
        name: prod.name,
        slug: prod.slug,
        description: prod.description,
        shortDescription: prod.shortDescription,
        category: prod.category,
        price: prod.price,
        isFree: prod.isFree,
        status: prod.status,
        sellerId: prod.sellerId,
        technologies: prod.technologies,
        tags: prod.tags,
        features: prod.features,
        requirements: prod.requirements,
        installation: prod.installation,
        documentation: prod.documentation,
        version: prod.version,
        rating: prod.rating,
        reviewCount: prod.reviewCount,
        salesCount: prod.salesCount,
        license: prod.license,
      },
    });
  }
  console.log("✅ Seeded 12 marketplace products.");

  // 6. Projects
  await prisma.project.create({
    data: {
      name: "AI Resume Screener & Ranking Engine",
      description: "Automated NLP-driven applicant screening tool that parses resumes and ranks candidate fit against custom job rubrics.",
      category: "ai-ml",
      status: ProjectStatus.ACTIVE,
      progress: 75,
      ownerId: "u1",
      githubRepo: "aarav/ai-resume-screener",
      technologies: ["Next.js", "Python", "FastAPI", "PostgreSQL", "Tailwind CSS"],
      isPublished: true,
      members: {
        create: [
          { userId: "u1", role: "Lead Architect" },
          { userId: "u2", role: "ML Engineer" },
        ],
      },
      tasks: {
        create: [
          { title: "Implement PDF Parser & OCR Pipeline", status: TaskStatus.DONE, priority: TaskPriority.HIGH, creatorId: "u1", assigneeId: "u2" },
          { title: "Cosine Similarity Scoring Algorithm", status: TaskStatus.DONE, priority: TaskPriority.URGENT, creatorId: "u1", assigneeId: "u2" },
          { title: "Multi-tenant Dashboard UI", status: TaskStatus.IN_PROGRESS, priority: TaskPriority.HIGH, creatorId: "u1", assigneeId: "u1" },
          { title: "Webhook & ATS Integrations", status: TaskStatus.TODO, priority: TaskPriority.MEDIUM, creatorId: "u1", assigneeId: "u1" },
        ],
      },
    },
  });

  await prisma.project.create({
    data: {
      name: "Design System & React Component Library",
      description: "High-performance accessible component kit built with Tailwind CSS, Radix UI, and Framer Motion.",
      category: "ui-kits",
      status: ProjectStatus.ACTIVE,
      progress: 90,
      ownerId: "u6",
      githubRepo: "sneha/react-design-system",
      technologies: ["React", "TypeScript", "Tailwind CSS", "Figma", "Storybook"],
      isPublished: true,
      members: {
        create: [
          { userId: "u6", role: "Design Lead" },
        ],
      },
    },
  });

  console.log("✅ Seeded projects.");

  // 7. Solution Requests (All 12 Real Database Records)
  const solutionRequestsData = [
    {
      id: "sr1",
      title: "AI-Powered Resume Screening System",
      description: "Need an automated NLP system that screens candidate resumes against job descriptions with ranking analytics.",
      problemStatement: "We receive 500+ resumes per job opening and manually reviewing them takes days. We need automated parsing, skill extraction, ATS scoring, and candidate ranking.",
      category: "ai-ml",
      solutionType: "ai_ml",
      difficulty: "advanced",
      status: SolutionRequestStatus.OPEN,
      clientId: "c1",
      budgetMin: 15000,
      budgetMax: 25000,
      isFixedPrice: false,
      preferredTechnologies: ["Python", "FastAPI", "React", "PostgreSQL"],
      requiredFeatures: ["Resume upload & parsing", "Job description matching", "Candidate ranking", "Skills extraction", "Analytics dashboard", "Export to CSV/Excel"],
      expectedDeliverables: ["Source code", "Deployed application", "API documentation", "Testing suite"],
      proposalCount: 8,
    },
    {
      id: "sr2",
      title: "Restaurant Online Ordering System",
      description: "Build a complete online ordering system for a restaurant chain with real-time delivery tracking.",
      problemStatement: "We operate 5 restaurants and require online ordering, live GPS delivery tracking, kitchen display system, and central admin.",
      category: "web",
      solutionType: "web",
      difficulty: "intermediate",
      status: SolutionRequestStatus.OPEN,
      clientId: "c2",
      budgetMin: 30000,
      budgetMax: 50000,
      isFixedPrice: false,
      preferredTechnologies: ["Next.js", "Node.js", "PostgreSQL", "Socket.io"],
      requiredFeatures: ["Menu management", "Online ordering", "Payment gateway", "Real-time order tracking", "Kitchen display", "Delivery management", "Customer accounts", "Admin dashboard"],
      expectedDeliverables: ["Full source code", "Deployment guide", "Admin manual"],
      proposalCount: 12,
    },
    {
      id: "sr3",
      title: "Appointment Booking System for Medical Clinic",
      description: "Need an appointment booking and patient management portal for a multi-speciality medical clinic.",
      problemStatement: "Our clinic handles 100+ daily patients. We need online scheduling, prescription generation, medical history, and SMS notifications.",
      category: "web",
      solutionType: "web",
      difficulty: "intermediate",
      status: SolutionRequestStatus.OPEN,
      clientId: "c3",
      budgetMin: 15000,
      budgetMax: 25000,
      isFixedPrice: true,
      preferredTechnologies: ["React", "Node.js", "PostgreSQL", "Tailwind CSS"],
      requiredFeatures: ["Online booking", "Patient records", "Prescription management", "Billing", "Doctor schedule management", "SMS reminders", "Report generation"],
      expectedDeliverables: ["Frontend & Backend code", "Database schema", "User manual"],
      proposalCount: 5,
    },
    {
      id: "sr4",
      title: "College Event Management Platform",
      description: "Build a platform for managing inter-college cultural & tech events, team registrations, and live scoring.",
      problemStatement: "We organize 20+ university events per semester. Need a centralized portal for team registration, schedule updates, scoring, and digital certificate generation.",
      category: "web",
      solutionType: "web",
      difficulty: "intermediate",
      status: SolutionRequestStatus.OPEN,
      clientId: "c4",
      budgetMin: 8000,
      budgetMax: 12000,
      isFixedPrice: false,
      preferredTechnologies: ["React", "Firebase", "Tailwind CSS"],
      requiredFeatures: ["Event listing", "Team registration", "Payment collection", "Schedule management", "Live scoring", "Results", "Certificate generation", "Leaderboard"],
      expectedDeliverables: ["Source code", "Deployment to Vercel"],
      proposalCount: 15,
    },
    {
      id: "sr5",
      title: "Automated Invoice Generator",
      description: "Need an automated system that generates compliant tax invoices from order streams automatically.",
      problemStatement: "We process 200+ daily orders and require automated GST tax calculation, branded PDF generation, email dispatch, and cloud archiving.",
      category: "automation",
      solutionType: "automation",
      difficulty: "intermediate",
      status: SolutionRequestStatus.OPEN,
      clientId: "c1",
      budgetMin: 10000,
      budgetMax: 20000,
      isFixedPrice: true,
      preferredTechnologies: ["Python", "Django", "React", "PostgreSQL"],
      requiredFeatures: ["Invoice template designer", "GST calculation", "PDF generation", "Email delivery", "Bulk processing", "Payment tracking", "Reports"],
      expectedDeliverables: ["Source code", "REST API", "Documentation"],
      proposalCount: 6,
    },
    {
      id: "sr6",
      title: "Customer Support AI Chatbot",
      description: "Build an AI chatbot with NLP query handling, knowledge base search, and human agent handoff.",
      problemStatement: "Our support desk receives 300+ daily inquiries. Need an automated conversational AI widget that handles common FAQs and escalates complex tickets.",
      category: "ai-ml",
      solutionType: "ai_ml",
      difficulty: "advanced",
      status: SolutionRequestStatus.OPEN,
      clientId: "c1",
      budgetMin: 30000,
      budgetMax: 50000,
      isFixedPrice: false,
      preferredTechnologies: ["Python", "FastAPI", "React", "OpenAI / HuggingFace"],
      requiredFeatures: ["NLP query understanding", "Knowledge base integration", "Multi-language support", "Human agent escalation", "Analytics dashboard"],
      expectedDeliverables: ["Full bot source code", "Embeddable web widget", "Training setup"],
      proposalCount: 4,
    },
    {
      id: "sr7",
      title: "Local Business Website Builder",
      description: "Create an intuitive drag-and-drop website generator tailored for local shops and service providers.",
      problemStatement: "Small business owners need high-speed storefront sites with pre-made templates for menus, maps, and appointment booking.",
      category: "web",
      solutionType: "web",
      difficulty: "advanced",
      status: SolutionRequestStatus.OPEN,
      clientId: "c2",
      budgetMin: 35000,
      budgetMax: 50000,
      isFixedPrice: false,
      preferredTechnologies: ["Next.js", "TypeScript", "Tailwind CSS"],
      requiredFeatures: ["Drag-and-drop builder", "Pre-made templates", "Contact forms", "Google Maps integration", "SEO optimization", "Custom domain support"],
      expectedDeliverables: ["Source code", "Admin builder portal"],
      proposalCount: 3,
    },
    {
      id: "sr8",
      title: "Attendance & Geo-fencing System",
      description: "Comprehensive employee and student attendance management with geo-location verification.",
      problemStatement: "We need to track field and campus attendance with GPS radius validation, leave management, overtime, and exportable timesheets.",
      category: "mobile",
      solutionType: "web",
      difficulty: "advanced",
      status: SolutionRequestStatus.IN_PROGRESS,
      clientId: "c1",
      budgetMin: 25000,
      budgetMax: 45000,
      isFixedPrice: false,
      preferredTechnologies: ["React Native", "Node.js", "PostgreSQL", "Mapbox"],
      requiredFeatures: ["Geo-fenced check-in", "Leave management", "Overtime calculation", "Shift management", "Reports", "Mobile app", "Payroll export"],
      expectedDeliverables: ["Mobile app & web portal", "PostgreSQL schema"],
      proposalCount: 9,
    },
    {
      id: "sr9",
      title: "Data Analytics Dashboard for E-commerce",
      description: "Build a real-time analytics dashboard visualizing sales velocity, churn, and inventory turnover.",
      problemStatement: "We need real-time visualization for product sales, customer segmentation cohorts, funnel drop-off, and inventory forecasts with custom date filters.",
      category: "data-science",
      solutionType: "data_analytics",
      difficulty: "intermediate",
      status: SolutionRequestStatus.OPEN,
      clientId: "c2",
      budgetMin: 15000,
      budgetMax: 25000,
      isFixedPrice: false,
      preferredTechnologies: ["React", "Python", "PostgreSQL", "D3.js"],
      requiredFeatures: ["Sales analytics", "Customer segmentation", "Product performance", "Inventory trends", "Custom date ranges", "Export reports", "Real-time updates"],
      expectedDeliverables: ["Frontend analytics app", "API integration guide"],
      proposalCount: 7,
    },
    {
      id: "sr10",
      title: "Inventory Management for Retail Chain",
      description: "Build an inventory management system with barcode scanning across multiple retail stores.",
      problemStatement: "We manage 3 retail stores and need centralized stock counts, automated store-to-store transfers, low-stock threshold alerts, and supplier POs.",
      category: "web",
      solutionType: "web",
      difficulty: "intermediate",
      status: SolutionRequestStatus.OPEN,
      clientId: "c2",
      budgetMin: 15000,
      budgetMax: 25000,
      isFixedPrice: true,
      preferredTechnologies: ["React", "Node.js", "PostgreSQL"],
      requiredFeatures: ["Barcode scanning", "Multi-store management", "Stock transfers", "Purchase orders", "Low stock alerts", "Supplier management", "Reports"],
      expectedDeliverables: ["Source code", "Deployment", "Staff training docs"],
      proposalCount: 10,
    },
    {
      id: "sr11",
      title: "Student Feedback & Survey Platform",
      description: "Build a platform for collecting and analyzing anonymous student course and faculty feedback.",
      problemStatement: "Universities need anonymous survey distribution, encrypted responses, faculty trend analysis, and automated executive report generation.",
      category: "web",
      solutionType: "web",
      difficulty: "beginner",
      status: SolutionRequestStatus.OPEN,
      clientId: "c4",
      budgetMin: 5000,
      budgetMax: 10000,
      isFixedPrice: true,
      preferredTechnologies: ["React", "Firebase", "Tailwind CSS"],
      requiredFeatures: ["Survey builder", "Anonymous submission", "Analytics dashboard", "Faculty reports", "Trend analysis", "Export data"],
      expectedDeliverables: ["Source code", "Admin setup manual"],
      proposalCount: 11,
    },
    {
      id: "sr12",
      title: "IoT Smart Parking System",
      description: "Build a smart parking management system with IoT sensor integration and vacancy mapping.",
      problemStatement: "Our campus parking lot holds 500 cars. We need ultrasonic sensor status streaming, real-time vacancy navigation on mobile, and digital spot reservation.",
      category: "automation",
      solutionType: "other",
      difficulty: "expert",
      status: SolutionRequestStatus.OPEN,
      clientId: "c4",
      budgetMin: 50000,
      budgetMax: 100000,
      isFixedPrice: false,
      preferredTechnologies: ["Python", "React Native", "MQTT", "PostgreSQL"],
      requiredFeatures: ["Sensor integration", "Real-time availability", "Mobile app", "Payment processing", "Navigation", "Analytics", "Reservation system"],
      expectedDeliverables: ["Hardware & firmware spec", "Mobile app & backend"],
      proposalCount: 2,
    },
  ];

  for (const sr of solutionRequestsData) {
    await prisma.solutionRequest.create({
      data: {
        id: sr.id,
        title: sr.title,
        description: sr.description,
        problemStatement: sr.problemStatement,
        category: sr.category,
        solutionType: sr.solutionType,
        difficulty: sr.difficulty,
        status: sr.status,
        clientId: sr.clientId,
        budgetMin: sr.budgetMin,
        budgetMax: sr.budgetMax,
        isFixedPrice: sr.isFixedPrice,
        preferredTechnologies: sr.preferredTechnologies,
        requiredFeatures: sr.requiredFeatures,
        expectedDeliverables: sr.expectedDeliverables,
        proposalCount: sr.proposalCount,
      },
    });
  }
  console.log("✅ Seeded all 12 solution requests into PostgreSQL.");
  console.log("🚀 Neon PostgreSQL database seed successfully completed!");
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
